crowdsecurity/hub

.index.json
scenarios/crowdsecurity/http-sqli-probing.md
scenarios/crowdsecurity/http-sqli-probing.yaml

Add a scenario that aims at detecting SQL injection probing.
Only detect patterns with low false positives chances and add distinct for extra anti-false positive measure :)
:warning: depends on https://github.com/crowdsecurity/crowdsec/pull/50 :warning:

Sqli probe scenario

---

collections/crowdsecurity/base-http-scenarios.md
collections/crowdsecurity/base-http-scenarios.yaml
scenarios/crowdsecurity/http-bad-user-agent.md
scenarios/crowdsecurity/http-bad-user-agent.yaml

Add our new scenarios to the http collection, out of the box security ftw

add our new HTTP scenarios to the http collection

---

collections/crowdsecurity/base-http-scenarios.yaml

fix https://github.com/crowdsecurity/crowdsec/issues/53

reduce title length to avoid making wizard look bad

---

scenarios/crowdsecurity/http-bad-user-agent.yaml

Fix the scenario to set the user_agent and the list items in Uppercase to be case insensitive

fix bad_user_agent scenario filter

---

.github/workflows/crowdsec-compat.yml

CI for crowdsec and hub

---

.github/workflows/crowdsec-compat.yml
parsers/s01-parse/crowdsecurity/vsftpd-logs.yaml

* Update CI 
* improve vsftpd parser

update CI 

---

scenarios/crowdsecurity/http-crawl-non_statics.yaml
scenarios/crowdsecurity/http-probing.yaml

Update http probing scenario to filter on non statis ressource

update scenario http probing

---

.index.json
collections/crowdsecurity/postfix.yaml
parsers/s01-parse/crowdsecurity/postfix-logs.yaml
scenarios/crowdsecurity/postfix-spam.yaml

add postfix spam collection

---

collections/crowdsecurity/postfix.md
collections/crowdsecurity/postfix.yaml
parsers/s01-parse/crowdsecurity/postfix-logs.yaml
parsers/s01-parse/crowdsecurity/postscreen-logs.yaml
parsers/s02-enrich/crowdsecurity/geoip-enrich.md
postoverflows/s01-whitelist/crowdsecurity/seo-bots-whitelist.md
scenarios/crowdsecurity/postfix-spam.yaml

import various commits into future release:
* postfix
* pinterest
* better disclaimer for maxmind

Import from master for future release

---

parsers/s01-parse/crowdsecurity/.tests/iptables-logs/acquis.yaml

Obvious fix on tests. No impact on user.

typo on test

---

.github/workflows/test_configurations.yaml

* fix the hub-tests command line
* be more specific at dispatch event

Fix the hub CI

---

.github/workflows/update-index.yml
.gitignore
parsers/s02-enrich/crowdsecurity/.tests/http-logs/bucket_input.yaml
parsers/s02-enrich/crowdsecurity/.tests/http-logs/config.yaml
parsers/s02-enrich/crowdsecurity/.tests/http-logs/parser_input.yaml
parsers/s02-enrich/crowdsecurity/.tests/http-logs/parser_results.json

* update .gitignore
* improve CI trigger
* add crowdsecurity/https-logs parser

add more tests

---

parsers/s02-enrich/crowdsecurity/.tests/geoip-enrich/config.yaml
parsers/s02-enrich/crowdsecurity/.tests/geoip-enrich/parser_input.yaml
parsers/s02-enrich/crowdsecurity/.tests/geoip-enrich/parser_results.json
scenarios/crowdsecurity/.tests/telnet-bf/bucket_input.yaml
scenarios/crowdsecurity/.tests/telnet-bf/buckets_results.json
scenarios/crowdsecurity/.tests/telnet-bf/config.yaml

* crowdsecurity/geoip-enrich
* crowdsecurity.telnet-bf

add geoip-enrich parser and telnet-bf scenario

---

collections/crowdsecurity/.tests/sshd/acquis.yaml
collections/crowdsecurity/.tests/sshd/auth.log
collections/crowdsecurity/.tests/sshd/bucket_result.json
collections/crowdsecurity/.tests/sshd/config.yaml
collections/crowdsecurity/.tests/sshd/parser_results.yaml

add ssh collection test

---

parsers/s01-parse/crowdsecurity/.tests/smb-logs/config.yaml
parsers/s01-parse/crowdsecurity/.tests/smb-logs/parser_input.yaml
parsers/s01-parse/crowdsecurity/.tests/smb-logs/parser_results.yaml

smb logs tests, with and without domain

smb-logs tests

---

.github/workflows/test_configurations.yaml
scenarios/crowdsecurity/.tests/http-bf-wordpress_bf/config.yaml

have the github pages pushed only on master

[CI] have the github pages pushed only on master

---

.github/workflows/test_configurations.yaml

fix the CI

---

parsers/s01-parse/crowdsecurity/.tests/apache2-logs/parser_results.yaml

fix user agent in apache2 parser

fix user agent

---

.exportedField/exported.go
.exportedField/go.mod
.github/workflows/generate_taxonomy.yaml
README.md
go.mod

Export field

---

scenarios/crowdsecurity/.tests/ssh-bf/bucket_input.yaml
scenarios/crowdsecurity/.tests/ssh-bf/bucket_results.yaml
scenarios/crowdsecurity/.tests/ssh-bf/config.yaml

add ssh-bf scenario

---

scenarios/crowdsecurity/.tests/smb-bf/bucket_input.yaml
scenarios/crowdsecurity/.tests/smb-bf/bucket_results.yaml
scenarios/crowdsecurity/.tests/smb-bf/config.yaml

add smb-bf scenarios

---

parsers/s01-parse/crowdsecurity/.tests/dovecot-logs/config.yaml
parsers/s01-parse/crowdsecurity/.tests/dovecot-logs/parser_input.yaml
parsers/s01-parse/crowdsecurity/.tests/dovecot-logs/parser_results.yaml
scenarios/crowdsecurity/.tests/dovecot-spam/bucket_input.yaml
scenarios/crowdsecurity/.tests/dovecot-spam/bucket_results.yaml
scenarios/crowdsecurity/.tests/dovecot-spam/config.yaml

add tests for dovecot collection

add tests for dovecot collection

---

.index.json
collections/crowdsecurity/dovecot.md
collections/crowdsecurity/dovecot.yaml
parsers/s01-parse/crowdsecurity/.tests/dovecot-logs/config.yaml
parsers/s01-parse/crowdsecurity/.tests/dovecot-logs/parser_input.yaml
parsers/s01-parse/crowdsecurity/.tests/dovecot-logs/parser_results.yaml
parsers/s01-parse/crowdsecurity/dovecot-logs.yaml
scenarios/crowdsecurity/.tests/dovecot-spam/bucket_input.yaml
scenarios/crowdsecurity/.tests/dovecot-spam/bucket_results.yaml
scenarios/crowdsecurity/.tests/dovecot-spam/config.yaml
scenarios/crowdsecurity/dovecot-spam.md
scenarios/crowdsecurity/dovecot-spam.yaml

- dovecot parser
- dovecot bruteforce/spam scenario
> by @ltsich

add dovecot collection 

---

postoverflows/s01-whitelist/crowdsecurity/seo-bots-whitelist.md

sync merge with https://github.com/crowdsecurity/sec-lists/pull/11

add qwant whitelists engine

---

.github/workflows/generate_taxonomy.yaml
.github/workflows/test_configurations.yaml
.github/workflows/test_configurations_on_hub-tests_changes.yaml
tests.sh

* naming improvement
* on change in hub, triggers CI for master + last tag of crowdsec and hub-tests
* on change in hub-tests master trigger ci

Improve CI

---

.github/workflows/test_configurations.yaml
.github/workflows/update-index.yml
parsers/s02-enrich/crowdsecurity/.tests/http-logs/parser_input.yaml
parsers/s02-enrich/crowdsecurity/.tests/http-logs/parser_results.yaml
parsers/s02-enrich/crowdsecurity/geoip-enrich.md
parsers/s02-enrich/crowdsecurity/http-logs.yaml

Scenarios+doc imp

---

.github/workflows/generate_taxonomy.yaml
.github/workflows/test_configurations.yaml

* trigger tests when there is a push or pull_request on master
* stop triggers on generate taxonomy when it's pull_request on master

gh actions fix

---

.index.json
scenarios/crowdsecurity/.tests/http-bad-user-agent/bucket_results.yaml
scenarios/crowdsecurity/http-bad-user-agent.yaml

this fixes a false positive where a user coming with a user agent that *contained* a substring that is a bad user agent would be banned : use regepx instead.

Improve http bad user agent : use regexp

---

.index.json
collections/crowdsecurity/wordpress.md
collections/crowdsecurity/wordpress.yaml
scenarios/crowdsecurity/http-wordpress_wpconfig.md
scenarios/crowdsecurity/http-wordpress_wpconfig.yaml

- detect variations around `wp-config` (such as what is done by wpscan)

Improve wordpress scenarios

---

.index.json
parsers/s02-enrich/crowdsecurity/whitelists.md
parsers/s02-enrich/crowdsecurity/whitelists.yaml

update the whitelist parser to include ipv6 localhost

---

.index.json
scenarios/crowdsecurity/dovecot-spam.yaml

dovecot is no http

---

.index.json
collections/crowdsecurity/sshd.md
collections/crowdsecurity/sshd.yaml
scenarios/crowdsecurity/.tests/ssh-slow-bf/bucket_input.yaml
scenarios/crowdsecurity/.tests/ssh-slow-bf/bucket_results.yaml
scenarios/crowdsecurity/.tests/ssh-slow-bf/config.yaml
scenarios/crowdsecurity/ssh-slow-bf.md
scenarios/crowdsecurity/ssh-slow-bf.yaml

fix #230 : add slow ssh bf detection

Slow ssh bf

---

.index.json
collections/crowdsecurity/opnsense.md
collections/crowdsecurity/opnsense.yaml

This will be installed by the "os-crowdsec" package in the post-install script.

opnsense collection

---

.index.json
scenarios/crowdsecurity/http-bad-user-agent.yaml

Use `RegexpInFile()` instead of `matches` `expr` because regexp are pre-compiled with `RegexpInFile()`

Fix bad user agent scenario

---

.index.json
collections/crowdsecurity/base-http-scenarios.yaml

fixes https://github.com/crowdsecurity/hub/issues/422

Make http-cve collection  part base-http-scenarios collection

---

.tests/sshesame/config.yaml
.tests/sshesame/parser.assert
.tests/sshesame/scenario.assert
.tests/sshesame/sshesame.log
collections/thespad/sshesame.md
collections/thespad/sshesame.yaml
parsers/s01-parse/thespad/sshesame-logs.md
parsers/s01-parse/thespad/sshesame-logs.yaml
scenarios/thespad/sshesame-honeypot.md
scenarios/thespad/sshesame-honeypot.yaml

A collection for the [sshesame](https://github.com/jaksi/sshesame) ssh honeypot.

Add sshesame collection

---

.github/workflows/test_configurations.yaml

Fix CI + avoid building crowdsec on every hubTest workflow run.

Improve hub tests ci

---

scenarios/LePresidente/gitea-bf.yaml

Disable debug mode

---

.github/workflows/update-index.yml

invalidate on the honeypots branch as well

invalidate on the honeypots branch as well

---

.index.json
collections/crowdsecurity/smb.md
collections/crowdsecurity/smb.yaml

fix #537: Addition of SMB collection

Addition of SMB collection

---

.tests/nginx-http-backdoor/config.yaml
scenarios/crowdsecurity/http-backdoors-attempts.yaml

Fix #580 
Had to fix nginx breaking tests once http-logs was installed it worked

Backdoors update

---

scenarios/crowdsecurity/http-apiscp-bf.yaml
scenarios/crowdsecurity/http-magento-bf.yaml
scenarios/crowdsecurity/http-magento-ccs-by-as.yaml
scenarios/crowdsecurity/http-magento-ccs-by-country.yaml
scenarios/crowdsecurity/http-magento-ccs.yaml
scenarios/crowdsecurity/thehive-bf.yaml

They quite noisy once installed cause debug has been left on

Change new scenarios debug = false

---

parsers/s02-enrich/crowdsecurity/http-logs.yaml

#533 Fix add .TS to file extensions

Add ts file to statics

---

scenarios/crowdsecurity/http-generic-bf.yaml

Reverts crowdsecurity/hub#628
creates issues for https://github.com/crowdsecurity/hub/pull/628#issuecomment-1381795722

Revert "add GET to 401 generic error"

---

.github/workflows/validate.yml

Validate schemas against crowdsec published schemas

Validate schemas

---

parsers/s01-parse/crowdsecurity/exim-logs.yaml

Exim parsers update to directadmin managed exim installs.

exim parsers updated

---

parsers/s01-parse/LePresidente/redmine-logs.yaml

Hi, 
Sorry about the PR so soon after a merge, just noticed I left the LogLevel "W" as hard coded at the start so just updated the parser to not include it incase it changes in the future.

Removed the fixed LogLevel of W at the start of the Parser for Redmine

---

parsers/s02-enrich/crowdsecurity/nextcloud-whitelist.yaml

Update whitelist for new issue

---

parsers/s01-parse/crowdsecurity/synology-dsm-logs.yaml

Partly #629 
Add range from 1-99 hopefully by this api revision we will not be around aymore :laugh:

Support other api values that are not just 7

---

.tests/netgear_rce/config.yaml

Update netgear RCE

---

parsers/s02-enrich/crowdsecurity/http-logs.yaml

Adding AVIF to http-logs.yaml

---

.tests/mariadb-logs/mariadb-logs.log
.tests/mariadb-logs/parser.assert
README.md
collections/crowdsecurity/mariadb.md
parsers/s00-raw/crowdsecurity/unifi-logs.md
parsers/s01-parse/corvese/apache-guacamole-logs.md
parsers/s01-parse/crowdsecurity/aws-cloudtrail.md
parsers/s01-parse/crowdsecurity/sysmon-logs.md
parsers/s01-parse/jusabatier/apereo-cas-audit-logs.md

```log
2023-11-21 19:42:20 134334 [Warning] Access denied for user 'root'@'34.140.248.32' (using password: NO)
```
https://mariadb.com/kb/en/server-system-variables/#log_warnings
```ini
log_warnings=3
```

Add a test for MariaDB and fix typos + MariaDB collection docs

---

.github/workflows/test_appsec_rules.yaml
scripts/appsec_vpatch_lint.py

- Fix appsec CI Linter
- Fix CI hubtest by specifing target

fix appsec CI linter

---

scenarios/crowdsecurity/http-dos-bypass-cache.yaml
scenarios/crowdsecurity/http-dos-invalid-http-versions.yaml

Fix a potential FP with http versions
Fix bucketify error with int conversion

HTTP Dos fixes

---

collections/crowdsecurity/iptables.yaml
collections/crowdsecurity/windows-firewall.yaml
collections/firewallservices/pf.yaml
contexts/crowdsecurity/firewall_base.yaml

It interesting for users to know what ports were scanned for alert context

[iptables/pf/windows] Add dst port as context

---

.index.json
postoverflows/s01-whitelist/crowdsecurity/cookiebot-whitelist.yaml

update last entry for ip dualstack use

update last entry for ip dualstack use

---

.github/workflows/test_appsec_rules.yaml
.github/workflows/waf-check.yaml

upgrade go version of CI

---

taxonomy/classifications.json

Adds both "hosts_malware" and "botnet" tag for botnet payloads

Add botnet taxonomy

---

.index.json
collections/ZoeyVid/npmplus.yaml

like done in the crowdsec docs

add crowdsecurity/appsec-generic-rules collection to NPMplus collection

---

.index.json
collections/crowdsecurity/plex.md
collections/crowdsecurity/plex.yaml
parsers/s02-enrich/crowdsecurity/plex-allowlist.md
parsers/s02-enrich/crowdsecurity/plex-allowlist.yaml

Add a collection/allowlist for Plex.

Basic plex support

---

taxonomy/scenarios.json

No more "ban IPs that are scanning us"

improve descriptions of some common scenarios

---

.index.json
contexts/crowdsecurity/appsec_base.yaml

cf. https://github.com/crowdsecurity/crowdsec/pull/3288
Add alert context rules to ensure default context matches existing one(s) that was relying on hardcoded rules

add alert context for appsec/waf

---

.index.json
scenarios/crowdsecurity/http-cve-2021-41773.yaml
scenarios/crowdsecurity/http-cve-2021-42013.yaml
taxonomy/scenarios.json

Found these two old scenarios with ugly descriptions while digging around in CTI

improve descriptions for apache path traversal

---

scenarios/crowdsecurity/http-generic-bf.yaml

fix: http generic bf add not verb check

---

.index.json
postoverflows/s01-whitelist/crowdsecurity/auditd-nix-wrappers-whitelist-process.md
postoverflows/s01-whitelist/crowdsecurity/auditd-nix-wrappers-whitelist-process.yaml

enhance: add Nix wrappers whitelist for auditd-sus-exec

---

taxonomy/classifications.json

We track this internally and it should be useful to CTI users aswell.

Add profile:spoofed_user_agent to taxonomy

---

.index.json
collections/crowdsecurity/openbsd.md
collections/crowdsecurity/openbsd.yaml

This add a basic collection based on the freebsd one.

add collections/openbsd and update index

---

taxonomy/false_positives.json

- Add cert.pl to taxonomy FP
- Move CISA and SSI.gouv.fr to false positive

Add Cert PL to taxonomy

---

scripts/scenario_taxonomy.py
taxonomy/scenarios.json

Fix the `git` command used to get a scenario file creation date

Fix scenarios taxonomy creation date

---

.tests/haproxy-logs/haproxy-logs.log
.tests/haproxy-logs/parser.assert
parsers/s01-parse/crowdsecurity/haproxy-logs.yaml

Added parser to haproxy to set bad_ssl_handshake logtype to lines cotaining SSL Handshake Failure
Fixes https://github.com/crowdsecurity/hub/issues/1262

HaProxy to set log_type for bad ssl handshakes

---

.tests/caddy-logs/parser.assert
parsers/s01-parse/crowdsecurity/caddy-logs.yaml

enhance: Remove remote_addr from caddy as not used and causing errors

---

.tests/gitlab-logs/parser.assert
parsers/s01-parse/timokoessler/gitlab-logs.yaml

As suggested by @LaurenceJJones in #1367

Update GitLab parser to use UnmarshalJSON

---

.appsec-tests/vpatch-git-config/test-vpatch-git-config.yaml
appsec-rules/crowdsecurity/vpatch-git-config.yaml

enhance: Add additional git folders to appsec rule

---

.appsec-tests/appsec-generic-test/appsec-generic-test.yaml
.appsec-tests/appsec-generic-test/config.yaml
appsec-rules/crowdsecurity/appsec-generic-test.yaml

match on HEAD too

---

taxonomy/classifications.json

https://github.com/crowdsecurity/cti_taxonomy_list/pull/563

add classification for bot detection

---

collections/ZoeyVid/npmplus.yaml

I also have a question, is it possible to rename ZoeyVid/npmplus to ZoeyVid/NPMplus or would this break exiting instances? Thanks!

add some more scenarios to the NPMplus collection by default
