- .github/workflows/update-blockers.yml
- .github/workflows/update-index.yml
- blockers.go
- ci.go
the idea is to have one main, and a `-targer` option that can be "blockers|configs|all"
> add a common main and '-target' option

- scenarios/crowdsecurity/http-bad-user-agent.yaml
The wordlist is case sensitive. Making case-sensitive matches limits the risk of false positives !
> make the check be case-sensitive

- parsers/s01-parse/crowdsecurity/apache2-logs.yaml
Fix apache2 parser, by specifing `pattern` instead of `name`
> fix apache2 grok pattern

- parsers/s01-parse/crowdsecurity/apache2-logs.yaml
- scenarios/crowdsecurity/http-generic-bf.md
- scenarios/crowdsecurity/http-generic-bf.yaml
- scenarios/crowdsecurity/http-probing.md
- scenarios/crowdsecurity/http-probing.yaml
> support apache errors log and http basic bruteforce

- .gitignore
- blockers.go
to fix that bug spotted in this [github action](https://github.com/crowdsecurity/hub/runs/1836654284?check_suite_focus=true)
> fix bug : when stable release don't have asset get zipball url instead

- parsers/s01-parse/crowdsecurity/postfix-logs.yaml
At least on Zimbra, but it can be configured on any postfix, the various smtpd listeners have a specific syslog ID set, eg : 
```
465    inet  n       -       n       -       -       smtpd
-o syslog_name=postfix/smtps
[...]
```
this result in such log lines
```
2021-02-28T11:58:36.591Z zmproxy.fws.fr postfix/smtps/smtpd[4136]: warning: unknown[192.168.7.5]: SASL LOGIN authentication failed: authentication failure
```
```
2021-02-28T11:58:40.127Z zmproxy.fws.fr postfix/submission/smtpd[4131]: warning: unknown[192.168.7.105]: SASL LOGIN authentication failed: another step is needed in authentication
```
This PR makes the postfix parsers works with Zimbra logs, or other postfix configured the same way.
> Catch smtps and submission postfix brutforce on Zimbra

- parsers/s01-parse/crowdsecurity/iptables-logs.yaml
This changes a few things for better iptables log handling  :
- Only parse kernel message containing IN= to prevent lots of unparsed lines in metrics
- Skip line if iptables decision is ACCEPT
- OUT= is not always present
- remove unused begining of regex, which can prevent parsing
Here are a few example of log lines which weren't parsed correctly and are now OK
From a Proxmox VE server, when we log accepted packets
```
2021-03-02T18:40:09.984Z pve-bkp kernel: 101 6 tap101i0-IN 02/Mar/2021:19:40:07 +0100 ACCEPT: IN=fwbr101i0 OUT=fwbr101i0 PHYSIN=fwln101i0 PHYSOUT=tap101i0 MAC=76:c8:d3:82:b5:d3:b6:d2:88:c3:15:e6:08:00 SRC=10.11.12.13 DST=14.15.16.17 LEN=60 TOS=0x00 PREC=0x00 TTL=56 ID=54553 PROTO=TCP SPT=36494 DPT=10051 SEQ=271997875 ACK=0 WINDOW=29200 SYN
```
Also from PVE, standard DROP. …
> Better handling of iptables logs

- parsers/s01-parse/crowdsecurity/nginx-logs.yaml
Most of my nginx logs were'nt parsed correctly by crowdsec. Find out that it's because the username field can be an empty string, and the %{NGUSER} grok pattern doesn't match empty strings. So, lets make this field optional
Sample logs which weren't parsed for me, and are now OK
```
crm.internal.fws.fr 10.118.22.3 - - [03/Mar/2021:17:34:44 +0100] "POST /index.php HTTP/2.0" 200 153 "https://crm.internal.fws.fr/index.php?module=Potentials&view=Detail&record=17092&app=SALES" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36" scheme="https"
crm.internal.fws.fr 10.118.22.3 - - [03/Mar/2021:17:34:44 +0100] "POST /index.php HTTP/2.0" 200 1669 "https://crm.internal.fws.fr/index.php?module=Potentials&view=Detail&record=17092&app=SAL …
```
> nginx username can be empty

- collections/crowdsecurity/traefik.md
- collections/crowdsecurity/traefik.yaml
- parsers/s01-parse/crowdsecurity/traefik-logs.md
- parsers/s01-parse/crowdsecurity/traefik-logs.yaml
- scenarios/crowdsecurity/traefik-bf.md
- scenarios/crowdsecurity/traefik-bf.yaml
This parser supports Traefik v2 logs both in JSON and [CLF](https://doc.traefik.io/traefik/observability/access-logs/#format)
Addresses #41 
**Testing (assuming the Crowdsec's testing environment)**:
1. Save a Traefik log file as `traefik.log`
2. Run `./crowdsec -c ./dev.yaml -dsn file://traefik.log -type traefik`
> Traefik access logs parser

- parsers/s02-enrich/crowdsecurity/http-logs.yaml
This adds the .brotli and .gz file extension to the valid resources list.
I think it maybe better to explicitly check for css.gz and css.brotli e.g., but with the `EXT` Regex that would require a change of that. I don't understand the consequences of that, so I'll let the team decide :)
This would close #330
> fix: file extensions for compressed resources

- collections/crowdsecurity/nextcloud.md
- parsers/s01-parse/crowdsecurity/nextcloud-logs.md
fix missing i in identifier in doc, use correct type for syslog/journald
> Fix typo in nextcloud parser and collection doc

- scenarios/crowdsecurity/http-crawl-non_statics.md
- scenarios/crowdsecurity/http-crawl-non_statics.yaml
This is a fix to solve the issue #366 
-- 
As discussed within the [discord thread](https://discord.com/channels/921520481163673640/938416827237806151),  limiting crawling to GET might be "ok" for now.
Happy to discuss additional methods like "POST / OPTIONS" but most likely they are not a crawling attack and therefore should go into another scenario.
> Http crawl-non-statics nextcloud fix

- .index.json
- collections/crowdsecurity/synology-dsm.yaml
collections/crowdsecurity/synology-dsm.yaml
contains a (bad) link to itself and made scenarios looping to try installing itself...
Signed-off-by: Kerma Gérald <gandalf@gk2.net>
> synology-dsm: remove collection (loop on self)

- scenarios/crowdsecurity/http-bf-wordpress_bf.yaml
Added check for 200 response code, as normal logins can be banned with the current rules
> Check for 200 response code in http-bf-wordpress_bf filter

- parsers/s01-parse/crowdsecurity/nginx-proxy-manager-logs.yaml
The original was not parsing my logs as the upstream_status would be returned as '-'. The GROK for that was set to NUMBER, I changed it to DATA and it now parses my NPM logs again.
Example of my log which was not parsing before the change, upstream_status position is set as a '-' character.
```
[15/Apr/2022:01:33:52 -0600] - - 403 - GET https x.y.com "/vZ0zgF2G.wwwacl" [Client 1.2.3.4] [Length 171] [Gzip 3.23] [Sent-to 4.3.2.1] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "-"
```
> Update nginx-proxy-manager parser

- .index.json
- postoverflows/s01-whitelist/crowdsecurity/cdn-whitelist.yaml
Fetched the same way as the V4 addresses. Method copied from `seo-bots-whitelist`.
Attempted to create tests for this but it seems post overflows aren't applied in `cscli hubtest` as no matter what I did I could not get it to apply even the unmodified version.
> Add CloudFlare V6 addresses to CDN whitelist

- parsers/s01-parse/crowdsecurity/nginx-logs.yaml
I had crowdsec logs filled with this error in production:
```
time="10-06-2022 17:37:45" level=error msg="unable to collect sources from bucket: while extracting scope from bucket crowdsecurity/nginx-req-limit-exceeded: scope is Ip but Meta[source_ip] doesn't exist"
```
Analysing the logs with:
```
crowdsec -dsn file:///var/log/nginx/lichess.error.log -type nginx -no-api
```
revealed that the parser couldn't handle this nginx log line:
```
2022/06/10 13:14:00 [error] 73917#73917: *9081828650 limiting requests, excess: 10.816 by zone "nodos_home_tier1", client: 82.64.134.116, server: lichess.org, request: "GET / HTTP/2.0", host: "lichess.org:443", referrer: "https://lichess.org/"
```
The culprit here is `host: "lichess.org:443"`.
Replacing it with just `host: "lichess.org"` fixed it.
So we …
> fix nginx logs pattern, add support for host:port

- parsers/s01-parse/crowdsecurity/postfix-logs.yaml
- parsers/s01-parse/crowdsecurity/postscreen-logs.yaml
This pull request adds the syslog names for haproxy protocol implementation in Mailcow.
Links to Mailcow config:
postscreen: [link](https://github.com/mailcow/mailcow-dockerized/blob/b6e3e7a658e19978bc94b96dd12fab56b11eefe9/data/conf/postfix/master.cf#L3-L5)
smtpd: [link](https://github.com/mailcow/mailcow-dockerized/blob/b6e3e7a658e19978bc94b96dd12fab56b11eefe9/data/conf/postfix/master.cf#L20-L27)
submission: [link](https://github.com/mailcow/mailcow-dockerized/blob/b6e3e7a658e19978bc94b96dd12fab56b11eefe9/data/conf/postfix/master.cf#L39-L47)
Log examples:
- Jul 24 23:50:25 test haproxy/postscreen[2953]: PREGREET 6 after 0 from [1.2.3.4]:22354: EHLO\r\n
- Jul 25 02:25:01 test haproxy/postscreen[3345]: NOQUEUE: reject: RCPT from [1.2.3.4]:61307: 550 5.7.1 Service unavailable; client …
> Update postfix & postscreen parsers for logs Mailcow/haproxy protocol

- parsers/s02-enrich/crowdsecurity/nextcloud-whitelist.md
- parsers/s02-enrich/crowdsecurity/nextcloud-whitelist.yaml
Fixes https://github.com/crowdsecurity/hub/issues/627
Hello! This PR fixes a couple more false positives when using Nextcloud:
* 404 responses when searching for files in the web interface, when Nextcloud requests preview images for files that don't have previews available
* 404 responses when uploading files via webDAV (it seems to be an intended part of the process)
It also fixes the formatting in `nextcloud-whitelist.md`.
Thank you to @LaurenceJJones for helping me with the syntax! 
You might note there are no changes to the tests for this parser. [I've posted on discord about that](https://discord.com/channels/921520481163673640/1069062913203118100/1069062913203118100): I initially updated the tests, but when I was verifying my changes and trying to work out which assertions to …
> feat: add more expressions to nextcloud-whitelist

- parsers/s01-parse/a1ad/meshcentral-logs.yaml
Issue found on discord by @LePresidente 
If the Pattern Syntax has the same name for multiple parsers, the first one is always used and not replaced.
So for example the first CUSTOMDATE will be reused instead of being unique to each parser
> change to unique custom parser variable

- parsers/s01-parse/LePresidente/gitea-logs.yaml
Added a match pattern to also pick up SSH Failed authentication attempts and not just the web failed authentication attempts.
The new grok pattern will match:
2023/02/25 20:26:14 modules/ssh/ssh.go:281:sshConnectionFailed() [W] [63fa641c-19] Failed authentication attempt from 1.2.3.4:57094
> Added match for SSH Failed authentication attempt

- .tests/nginx-mail-logs/nginx-mail-logs.log
- .tests/nginx-mail-logs/parser.assert
- parsers/s01-parse/hitech95/nginx-mail-logs.yaml
This fixes a bug in the nginx-mail-logs parser
When using starttls the resulting log lines look like `client: <ip> using starttls, server....`
However the original pattern could only match `client: <ip>, server....`, so any starttls logs were missed.
> Fix nginx mail logs when using tls

- postoverflows/s00-enrich/crowdsecurity/rdns.yaml
Cause we have auditd and everything now we should be a little bit more specific incase a user creates a scenario that is not a Ip based remediation is true.
Edit: checking enricher code it will fail, but lets save us time by bypassing the filter
> Update rDNS filter to check if scope is Ip

- parsers/s01-parse/LePresidente/authelia-logs.yaml
First of all - Thanks for the great work !
It seems like we have to remove the start/end of the line matching filter to allow container logs to be parsed.
Similar to https://github.com/crowdsecurity/hub/pull/818
> fix(authelia): Remove ^ from the patterns to allow container log parsing

- collections/crowdsecurity/iptables.md
It wasnt clear to a community member how to achieve reading kernal message without rsyslog.
Add example to collection.
> Add journalctl example to iptables

- .github/workflows/update-index.yml
- make only one query to AWS API to invalidate all changed files
- Retry up to 3 times
- Upgrade configure-aws-credentials action to v4
- Always run the invalidation, even on dev branches
> Improve cache invalidation job

- waf-check/config.go
- waf-check/manager.go
- waf-check/result.go
Add `-output` & `-status-code` options and fixes a command line help message.
> Add -output and -status-code options

- collections/jbowdre/miniflux.md
Github-flavored > [!NOTE] alerts don't render correctly in the Hub.
This change fixes the note formatting and moves the note below the aquisition example to more closely match the layout used in other collections.
> fix formatting in miniflux collection readme

- .github/workflows/appsec_vpatch_lint.yaml
- .github/workflows/update-index.yml
- .github/workflows/update_taxonomy.yaml
When upgrading actions/checkout from v1 to v4, the fetch-depth parameter changed to 1 (from 0 previously).
This means that only the most recent commit was fetched, preventing the proper detection of changed files.
Revert back to the old behavior by setting fetch-depth to 0 to fetch the entire repo (probably overkill, 2 might work as well).
Also delete the long-unused `hub-tests` submodule to remove some warnings in the cleanup of the checkout action.
> Fix ub cache invalidation

- postoverflows/s01-whitelist/crowdsecurity/cdn-qc-whitelsit.md
- postoverflows/s01-whitelist/crowdsecurity/cdn-qc-whitelsit.yaml
Adding QUIC.cloud, Litespeeds main own CDN, as a new post-overflow scenario for CDN whitelists.
> Adding QUIC.cloud CDN to the postoverflow scenarios

- .tests/pterodactyl-wings-bf/pterodactyl-wings-bf.log
- .tests/pterodactyl-wings/parser.assert
- .tests/pterodactyl-wings/pterodactyl-wings-bf.log
- parsers/s01-parse/lourys/pterodactyl-wings-logs.yaml
My pterodactyl wings logs have a space character in front of WARN, add support for whitespace to appear before WARN and it can still properly parse the logfile.
> Update pterodactyl-wings-logs parser

- .appsec-tests/generic-wordpress-uploads-php/config.yaml
- .appsec-tests/generic-wordpress-uploads-php/generic-wordpress-uploads-php.yaml
- .index.json
- appsec-rules/crowdsecurity/generic-wordpress-uploads-php.yaml
- collections/crowdsecurity/appsec-generic-rules.yaml
- collections/crowdsecurity/appsec-wordpress.yaml
~TODO: Need to manually run index workflow on fork~
> enhance: add generic wordpress uploads directory execution of php like files

- .github/workflows/update-index.yml
As crowdsec and the console both now use HAPI to get the hub content, the index file that was served directly from github through cloudfront is not accessed directly anymore, so we can remove the cache invalidation: this also removes a secret, which should allow the index update job to run properly on forks.
If we need to update the hub for an older version of crowdsec (which rarely happens), we'll need to manually run the cache invalidation.
> remove cloudfront invalidation

- scenarios/crowdsecurity/suricata-alerts.yaml
- taxonomy/scenarios.json
Set confidence to 1 and spoofable to 3 for suricata scenarios
> Review suricata scenarios confidence and spoofable

- collections/crowdsecurity/appsec-generic-rules.yaml
- collections/crowdsecurity/appsec-virtual-patching.yaml
- collections/crowdsecurity/appsec-wordpress.yaml
- scenarios/crowdsecurity/appsec-native.yaml
- scenarios/crowdsecurity/appsec-vpatch.yaml
The change aims at the following:
- add a scenario for native rules with a lower confidence score
- ensure the vpatch scenario doesn't pick up on native rules, but will pick up any other rules (both vpatch and user-defined)
In the future we might want to find a better way to separate user-defined rules and crowdsec's provided vpatch rules.
> Enhance: appsec sceanario split and collection updates

- parsers/s02-enrich/crowdsecurity/whitelists.md
- parsers/s02-enrich/crowdsecurity/whitelists.yaml
This PR expands the whitelist from just 127.0.0.1 to the entire 127.0.0.0/8 loopback range as defined in [RFC5735](https://www.rfc-editor.org/rfc/rfc5735) and [RFC1122 Section 3.2.1.3](https://www.rfc-editor.org/rfc/rfc1122#section-3.2.1.3). According to these RFCs, all addresses in this range are reserved for loopback and should never appear on any network, making them safe to whitelist.
For IPv6, the whitelist correctly includes only ::1/128 as specified in [RFC5156](https://www.rfc-editor.org/rfc/rfc5156).
I just bug-hunted for several days, `127.0.0.53` was being banned, which caused DNS(systemd-resolved) to break, which caused my auto-install script for crowdsec parsers/collections to fail, which caused this whitelist to not be installed, which then caused bans on `127.0.0.1`, which …
> Whitelist whole ipv4 loopback cidr instead of just 127.0.0.1

- collections/MrShippeR/filebrowser.md
- collections/MrShippeR/filebrowser.yaml
- parsers/s01-parse/MrShippeR/filebrowser-logs.md
- parsers/s01-parse/MrShippeR/filebrowser-logs.yaml
Hello,
I'm author of Filebrowser collection. Comming with update.
Main point of this update is to fix **pattern_syntax** of parser. Changing `%{IPV4:source_ip}` to `%{IP:source_ip}`. So it will process both IPv4 and IPv6 adresess.  
_Giving credit to ollieblazejames@gmail.com for idea and realization._
> Filebrowser Collection allow parsing IPv6

- .appsec-tests/generic-no-user-agent/config.yaml
- .appsec-tests/generic-no-user-agent/generic-no-user-agent.yaml
- appsec-configs/crowdsecurity/appsec-default.yaml
- appsec-configs/crowdsecurity/generic-rules.yaml
- appsec-rules/crowdsecurity/experimental-no-user-agent.yaml
- appsec-rules/crowdsecurity/generic-no-user-agent.yaml
- collections/crowdsecurity/appsec-generic-rules.yaml
- taxonomy/scenarios.json
This rule detects if the incoming request has no useragent, typically you would combine this with an empty string check, however, nginx siliently drops empty headers so there no point having this plus nuclei makes this impossible to test 😓 .
Also HEAD requests by RFC do not need to send a usergent, hence these are omitted by the method check.
> enhance: Appsec no user agent typical of bot or raw http attack

- collections/LePresidente/jellyseerr.yml
- parsers/s02-enrich/crowdsecurity/jellyseerr-whitelist.md
- parsers/s02-enrich/crowdsecurity/jellyseerr-whitelist.yaml
- scenarios/LePresidente/jellyseerr-bf.yaml
Fix user enum leakspeed is less than generic BF leakspeed causing user enum scenario to be impossible to trigger except at the exact same time as BF scenario. Add Jellyseerr whitelist to prevent http-crawl-non_statics false positives which will fix #1123.
The user enumeration BF scenario is distinct by username and should have a slower leakspeed in order for it to do anything. Otherwise, the generic BF scenario will always trigger first. This appears to be a typo as the .md file says the leakspeed on the user enumeration BF should be 1m.
Add Jellyseerr whitelist which works for me and others locally as mentioned in #1123. I added it to the Jellyseerr collection in this PR but I am not sure how to add tests for it. Looking for help if tests are needed.
> Fix Jellyseerr user enum BF and add Jellyseerr whitelist
